<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you interested in programming?' => '',
    'Birth Date' => '',
    'CONTINUE FORM' => '',
    'Complete form in order for us to gather info about you.' => '',
    'Dont know any of these' => '',
    'Female' => '',
    'Form' => '',
    'Form in progress...' => '',
    'Gender' => '',
    'Hello there!' => '',
    'Home' => '',
    'ID' => '',
    'Img Path' => '',
    'Intrested In Programming' => '',
    'Limit is 500KB' => '',
    'Male' => '',
    'Name' => '',
    'Next' => '',
    'No' => '',
    'Programming Languages' => '',
    'START FORM' => '',
    'The requested page does not exist.' => '',
    'User ID' => '',
    'What programming languages do you know?' => '',
    'Whats your name?' => '',
    'Yes' => '',
    'Your Image' => '',
    'Your birth date:' => '',
    'Your gender:' => '',
    'Your picture' => '',
    'Your pictures' => '',
    'Complete Form' => '@@@@',
    'P Lang ID' => '@@@@',
    'Your Name' => '@@@@',
];
