<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '',
    'Limit is 500KB' => 'Maximalus failo limitas - 500KB',
    'Complete Form' => '@@Užpildykite formą@@',
    'P Lang ID' => '@@@@',
    'Your Name' => '@@Jūsų vardas@@',
    'Are you interested in programming?' => 'Ar domitės programavimu?',
    'Birth Date' => 'Gimimo data',
    'CONTINUE FORM' => 'Testi formą',
    'Complete form in order for us to gather info about you.' => 'Užpildykite trumpą formą.',
    'Dont know any of these' => 'Nemoku nė vienos',
    'Female' => 'Moteris',
    'Form' => 'Forma',
    'Form in progress...' => 'Forma pildoma...',
    'Gender' => 'Lytis',
    'Hello there!' => 'Sveiki!',
    'Home' => 'Pagrindinis',
    'Img Path' => 'Nuotraukos linkas',
    'Intrested In Programming' => 'Ar programavimas domina?',
    'Male' => 'Vyras',
    'Name' => 'Vardas',
    'Next' => 'Kitas',
    'No' => 'Ne',
    'Programming Languages' => 'Programavimo kalbos',
    'START FORM' => 'PRADĖTI FORMĄ',
    'The requested page does not exist.' => 'Reikiamas puslapis neegzistuoja',
    'User ID' => 'Vartotojo ID',
    'What programming languages do you know?' => 'Kokias programavimo kalbas mokate?',
    'Whats your name?' => 'Koks jūsų vardas?',
    'Yes' => 'Taip',
    'Your Image' => 'Jūsų nuotrauka',
    'Your birth date:' => 'Jūsų gimimo data:',
    'Your gender:' => 'Jūsų lytis:',
    'Your picture' => 'Jūsų nuotrauką:',
    'Your pictures' => 'Jūsų nuotrauka',
];
